apiVersion: v2
name: gotosocial
description: A Helm chart for Kubernetes
icon: https://docs.gotosocial.org/en/latest/assets/sloth.png
home: https://github.com/superseriousbusiness/gotosocial

type: application
# Chart Version
version: "0.3.0"
# gotosocial version
appVersion: "0.5.2"

maintainers:
  - name: 0hlov3
    email: 0hlov3@protonmail.com
    url: https://schoenwald.me

dependencies:
  - name: postgresql
    version: ~11.0.06
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

annotations:
  artifacthub.io/changes: |
    - Move everything to secrets
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: gotosocial
      image: superseriousbusiness/gotosocial:latest
